# Generated by Django 3.2.5 on 2022-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goldprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.CharField(max_length=100)),
                ('cnum', models.CharField(max_length=100)),
                ('eml', models.CharField(max_length=100)),
            ],
        ),
    ]
