# Generated by Django 3.2.5 on 2022-03-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dril', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldprice',
            old_name='cnum',
            new_name='cnam',
        ),
        migrations.RenameField(
            model_name='goldprice',
            old_name='nam',
            new_name='cno',
        ),
        migrations.AddField(
            model_name='goldprice',
            name='pas',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldprice',
            name='snam',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldprice',
            name='usr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
